### ISSUE TITLE
Shuffling collections of files?

### ISSUE THREAD

**Issue by Holmes5** [alexandres/terashuf#7]
Does the current interface support shuffling a large corpus that is broken down into many files, which is a very common situation in practice? I don't really know C++, so it would be difficult for me to implement this feature myself, but I might do it if no one else does. One can of course cat the files together and split them, but that creates additional disk space overhead.

**Comment by Holmes5** [comment]
I would also like the option to output a set of files instead of a single file.

**Comment by alexandres** [comment]
Hi!

Are you ok with a bash solution? If so, to shuffle multiple files and get a single shuffled output file:

`$> cat file1.txt file2.txt etc | ./terashuf > shuffled.txt` 

To shuffle and get multiple output files,

`$> cat file1.txt file2.txt etc | ./terashuf | split -l 100000 - shuffled.txt.` 

will return files named `shuffled.txt.aa, shuffled.txt.ab, ...` with 100k lines each. 

If you want 1G files (independent of number of lines), try

`$> cat file1.txt file2.txt etc | ./terashuf | split -b 1G - shuffled.txt.` 

See https://man7.org/linux/man-pages/man1/split.1.html for more information on the `split` command.

**Comment by Holmes5** [comment]
Thank you for your prompt reply! I had thought of using `cat` and `split`, and it works, but my concern was that it could use more disk space? Would either step of this result in substantial extra disk space being used, or does the piping solve this problem (i.e., does it effectively avoid creating a concatenated file on disk, even temporarily)?

**Comment by alexandres** [comment]
You can have a look at coreutils source code for both cat and split to
confirm. However, I see no reason why they should create temporary files.
Also see
https://superuser.com/questions/81679/does-pipe-have-to-write-temporary-file

**Comment by Holmes5** [comment]
This is an acceptable solution. For the record, I think --line-bytes is the correct option for split rather than -b if you want files of approximately a particular size with complete lines. (but it's not a huge deal given that it only affects a couple dozen of my hundreds of millions of lines).

**Comment by alexandres** [comment]
You are correct! Thanks for catching that.

I will add this information to the README.

**Comment by alexandres** [comment]
Info added in 29a65ed
