### ISSUE TITLE
how to use SKIP.

### ISSUE THREAD

**Issue by wshwhyu** [alexandres/terashuf#8]
SKIP (int): how many lines to skip at beginning of input; defaults to 0. When shuffling CSV files, set to 1 to preserve header.

Do I need to add this parameter when executing the command in the command line? Could you give me an example?
Thank you very much.

**Comment by alexandres** [comment]
Hi @wshwhyu !

If you are shuffling a CSV file named `input.csv`, generating output file `shuffled.csv`, you'd use it as follows: 

`$> head -1 input.csv > shuffled.csv; SKIP=1 ./terashuf < input.csv >> shuffled.csv`

You could also use just GNU tools:

`$> head -1 input.csv > shuffled.csv; tail  -n +2  input.csv | ./terashuf >> shuffled.csv`

Hope that helps.

**Comment by wshwhyu** [comment]
Thank you very much. My problem has been resolved.
